
= Swift-DataSpaces Integration

The point of this module is to demonstrate tight integration between Swift/T and DataSpaces, allowing Swift/T workflows to access DataSpaces efficiently through the DataSpaces C API.

== Architecture

. Swift/T can call directly into C functions if they have a Tcl wrapper
. We use SWIG to generate these wrappers
. We then can write Tcl programs that use DataSpaces
. We can produce nice Swift/T functions that use the Tcl functions
. Then we can write Swift/T workflows that access DataSpaces

== File index

SDS = Swift-DataSpaces

+sds.c+::
Light wrapper around the DataSpaces init/put/get/finalize calls.  These functions simplify the API for SWIG

+sds.h+::
The header for sds.c processed by SWIG

+sds.i+::
SWIG input file- points to sds.h , creates Tcl extension wrapper sds_wrap.c

+Makefile+::
Compiles sds.c and sds_wrap.c into libsds.so , which links against Tcl and DataSpaces.  Creates a loadable Tcl package.

+make-package.tcl+::
Makes the Tcl package

+pkgIndex.tcl+::
The Tcl package index

+test-ds.tcl+::
Tests the Tcl sds package

+run-test-ds.tcl+::
Runs test-ds.tcl

+run-test-sds-1.sh+::
Runs the Swift/T test test-sds-1.swift

+test-sds-1.swift+::
A simple Swift/T put/get test

+sds.swift+::
Swift/T wrappers for the Tcl functions

== Usage

=== New Swift/T

. Check out Swift/T branch +dataspaces+
. If Swift/T is already installed, just do +make install+ for ADLB and Turbine

=== DataSpaces

. May turn on DEBUG in dart/debug.h

=== SDS

. Edit Makefile to set Tcl and DataSpaces locations
. Run +make+
. Run +./run-test-ds.tcl+

== Transcripts

=== Swift/T test

----
$ ./run-test-sds-1.sh
dataspaces_server running: DS_SERVER_PID=19507
[0] sds_kv_put: key1=value1
[1] sds_kv_get: key1 (100)
[1] sds_kv_got: key1=value1
[0] trace: s: ,value1
killing dataspaces_server
----

NOTE: We use the location syntax to force the put and get tasks to
run on separate ranks.  You can simply comment out this syntax
and the workflow will still work.

=== Pure Tcl test

In one shell, do:
----
$ dataspaces_server -s 1 -c 2
----

Then, in another shell, do:
----
$ ./run-test-ds.sh
----

NOTE: Kill and restart the server after each test.
